version: "3.5"
services:

  vaultwarden:
    image: vaultwarden/server
    container_name: vaultwarden
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./data:/data
    env_file: .env
    networks:
      - net-vaultwarden

networks:
  net-vaultwarden:
    external: true
