version: "3.5"
services:

    vaultwarden:
        image: vaultwarden/server
        restart: unless-stopped
        user: 1000:1000
        volumes:
            - ./data:/data
        env_file:
            - ./data/docker-config.env
        networks:
            - net-vaultwarden

networks:
    net-vaultwarden:
        external: true
